((LAMBDA (FF X) (FF FF X))
 (LAMBDA (FF X) (COND ((ATOM X) X) ((QUOTE T) (FF FF (CAR X)))))
 (QUOTE ((A) B C)))
(((LAMBDA (F)
    ((LAMBDA (G) (F (LAMBDA (V) ((G G) V))))
     (LAMBDA (G) (F (LAMBDA (V) ((G G) V))))))
  (LAMBDA (RECUR)
    (LAMBDA (W) (COND ((ATOM W) W) ((QUOTE T) (RECUR (CAR W)))))))
 (QUOTE ((A) B C)))
(DEFINE FF . (LAMBDA (X) (COND ((ATOM X) X) ((QUOTE T) (FF (CAR X))))))
(FF (QUOTE ((A) B C)))
((LAMBDA (GG X) (GG X))
 (LAMBDA (X) (COND ((ATOM X) X) ((QUOTE T) (GG (CAR X)))))
 (QUOTE ((A) B C)))
